# Generated by Django 5.2.1 on 2025-05-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('location', models.CharField(max_length=100)),
                ('tickit', models.IntegerField(help_text='5분 단위로 입력해주세요. 예: 5, 10, 15, ...')),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('WAITING', '헬퍼 찾는 중'), ('IN_PROGRESS', '진행 중'), ('DONE', '거래 완료')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_posts', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
