# Generated by Django 5.2.3 on 2025-06-21 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_friend'),
        ('posts', '0002_post_task_completed_at_post_transaction_finished_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
