# Generated by Django 5.2.1 on 2025-06-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('waiting', '헬퍼찾는중'), ('chatting', '채팅중'), ('in_progress', '거래중'), ('task_completed', '수행 완료'), ('done', '거래완료')], max_length=20),
        ),
    ]
