# Generated by Django 5.2.3 on 2025-06-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_timehistory_balance_after'),
        ('friends', '0002_friendrequestnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequestnotification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_alarm', to='accounts.profile'),
        ),
    ]
