# Generated by Django 5.2.1 on 2025-06-21 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0002_post_task_completed_at_post_transaction_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timehistory',
            name='post_id',
        ),
        migrations.AddField(
            model_name='timehistory',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.post'),
        ),
    ]
