# Generated by Django 5.2.1 on 2025-06-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_friend'),
        ('accounts', '0002_remove_timehistory_post_id_timehistory_post'),
    ]

    operations = [
    ]
