# Generated by Django 5.2.1 on 2025-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250621_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reserved_time',
            field=models.IntegerField(default=0),
        ),
    ]
