# Generated by Django 5.2.1 on 2025-06-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timehistory',
            name='type',
            field=models.CharField(choices=[('plus', '플러스'), ('minus', '마이너스'), ('tip', '팁')], max_length=10),
        ),
    ]
