# Generated by Django 5.2.1 on 2025-06-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_reserved_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reserved_time',
            new_name='available_time',
        ),
    ]
