# Generated by Django 5.2.1 on 2025-06-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_reserved_time_profile_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timehistory',
            name='balance_after',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
