# Generated by Django 5.2.1 on 2025-06-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email_domain',
            field=models.CharField(default='dgu.ac.kr', max_length=100),
            preserve_default=False,
        ),
    ]
